version: '3.9'

services:
    db:
        platform: linux/amd64
        container_name: db
        restart: always
        healthcheck:
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"nocodb\""
            timeout: 2s
        image: timescale/timescaledb-ha:pg16
        ports: 
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./002_init_nocodb.sql:/docker-entrypoint-initdb.d/002_init_nocodb.sql
        env_file:
            - .env

volumes: 
    db-data: {}